% analysis
t_s = A(:,1);
figure(1)
subplot(3,1,1)
plot(t_s,A(:,20)-V_b(:,1))
ylabel('E_{b,x} (m/s)')
xlabel('t (s)')
title('V_{b,x} error')
subplot(3,1,2)
plot(t_s,A(:,21)-V_b(:,2))
ylabel('E_{b,y} (m/s)')
xlabel('t (s)')
title('V_{b,y} error')
subplot(3,1,3)
plot(t_s,A(:,22)-V_b(:,3))
ylabel('E_{b,z} (m/s)')
xlabel('t (s)')
title('V_{b,z} error')
figure(2)
subplot(3,1,1)
plot(t_s,A(:,2)-V_I(:,1))
ylabel('E_{I,z} (m/s)')
xlabel('t (s)')
title('V_{I,z} error')
grid on
subplot(3,1,2)
plot(t_s,A(:,3)-V_I(:,2))
ylabel('E_{I,z} (m/s)')
xlabel('t (s)')
title('V_{I,z} error')
grid on
subplot(3,1,3)
plot(t_s,A(:,4)-V_I(:,3))
ylabel('E_{I,z} (m/s)')
xlabel('t (s)')
title('V_{I,z} error')
grid on
figure(3)
subplot(3,1,1)
plot(t_s,A(:,5)-omega(:,1))
ylabel('E_{b,x} (RAD/s)')
xlabel('t (s)')
title('{\omega}_{b,x} error')
grid on
subplot(3,1,2)
plot(t_s,A(:,6)-omega(:,2))
ylabel('E_{b,y} (RAD/s)')
xlabel('t (s)')
title('{\omega}_{b,y} error')
grid on
subplot(3,1,3)
plot(t_s,A(:,7)-omega(:,3))
ylabel('E_{b,z} (RAD/s)')
xlabel('t (s)')
title('{\omega}_{b,z} error')
grid on
figure(4)
subplot(3,1,1)
plot(t_s,A(:,8)-X_I(:,1))
ylabel('E_{I,x} (m)')
xlabel('t (s)')
title('X_{I,x} error')
subplot(3,1,2)
plot(t_s,A(:,9)-X_I(:,2))
ylabel('E_{I,y} (m)')
xlabel('t (s)')
title('X_{I,y} error')
subplot(3,1,3)
plot(t_s,A(:,10)-X_I(:,3))
ylabel('E_{I,z} (m)')
xlabel('t (s)')
title('X_{I,z} error')
Euler_A = zeros(size(DCM));% R_BI
for i =1: max(size(A))
    R = [A(i,11:13)' A(i,14:16)' A(i,17:19)'];% R_IB
    Euler_A(:,:,i)= R*reshape(DCM(:,:,i),3,3);
end

figure
subplot(3,1,1)
plot(t_s,A(:,5),t_s,omega(:,1))
legend('Solver','Simulink')
ylabel('E_{b,x} (RAD/s)')
xlabel('t (s)')
title('{\omega}_{b,x}')
grid on
subplot(3,1,2)
plot(t_s,A(:,6),t_s,omega(:,2))
legend('Solver','Simulink')
ylabel('E_{b,y} (RAD/s)')
xlabel('t (s)')
title('{\omega}_{b,y}')
grid on
subplot(3,1,3)
plot(t_s,A(:,7),t_s,omega(:,3))
legend('Solver','Simulink')
ylabel('E_{b,z} (RAD/s)')
xlabel('t (s)')
title('{\omega}_{b,z}')
grid on